In [2]:
import numpy as np

In [5]:
a = np.array ([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis=0)

In [8]:
mean_a


array([2. , 8.4])

In [9]:
a_centered = np.subtract (a, mean_a )

In [10]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [16]:
b = np. array ([-1., 0., 1., 1., -1.])
c = np. array ([-2.4, -0.4, 2.6, 1.6, -1.4])

In [18]:
a_centered_sp = np.dot(b,c)

In [19]:
a_centered_sp

8.0

In [20]:
coviar = a_centered_sp//4

In [21]:
coviar

2.0

In [22]:
AT = a.transpose()

In [23]:
AT

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [24]:
d = np.cov(AT)

In [25]:
d

array([[1. , 2. ],
       [2. , 4.3]])